version: "3.8"

services:
  app:
    container_name: dix_app_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0
    volumes:
      - ./api:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=dix
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    container_name: dix_app_db
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=dix
      - MYSQL_USER=dix
      - MYSQL_PASSWORD=dixapp
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
